name = "AffineInvariantMCMC"
uuid = "a0f608ac-68d0-5108-ad9a-0cdca73324f3"
version = "1.2.2"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RobustPmap = "27aeedcb-f738-516b-a0b8-3211cf1146e5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
JLD2 = "0.4, 0.5, 1"
ProgressMeter = "1"
RobustPmap = "1"
Statistics = "1"
julia = "1.9"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Statistics", "Test", "Random"]